token: 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
DS-Video-Streaming-System:
  url: https://github.com/AnjanaIshara/DS-Video-Streaming-System.git
  branches:
  - main
Bankers-Algorithm-in-Cpp:
  url: https://github.com/IsuruMS/Bankers-Algorithm-in-Cpp.git
  branches:
  - master
brainSlicer:
  url: https://github.com/IsuruMS/brainSlicer.git
  branches:
  - main
Calculate-formulae-using-stack:
  url: https://github.com/IsuruMS/Calculate-formulae-using-stack.git
  branches:
  - master
codeBase:
  url: https://github.com/IsuruMS/codeBase.git
  branches:
  - master
Find-All-Occurances-of-A-Number-In-a-Matrix:
  url: https://github.com/IsuruMS/Find-All-Occurances-of-A-Number-In-a-Matrix.git
  branches:
  - master
Football_Scorecard:
  url: https://github.com/IsuruMS/Football_Scorecard.git
  branches:
  - master
git_interface:
  url: https://github.com/IsuruMS/git_interface.git
  branches:
  - main
Implementation-of-3-Pipes:
  url: https://github.com/IsuruMS/Implementation-of-3-Pipes.git
  branches:
  - master
inspinia:
  url: https://github.com/IsuruMS/inspinia.git
  branches:
  - gh-pages
  - master
IntroJenkins:
  url: https://github.com/IsuruMS/IntroJenkins.git
  branches:
  - master
  - release/1.0.2
  - release/1.0.3
  - release/1.0.23
  - release/1.1
  - release/1.2
  - release/1.2.1
  - release/1.2.2
  - release/1.3.0
  - release/1.3.1
  - release/1.3.12
Linked-List:
  url: https://github.com/IsuruMS/Linked-List.git
  branches:
  - master
Matrix-Multiplication-Multithreaded:
  url: https://github.com/IsuruMS/Matrix-Multiplication-Multithreaded.git
  branches:
  - master
MonteCarloPiEstimation:
  url: https://github.com/IsuruMS/MonteCarloPiEstimation.git
  branches:
  - master
Printing-Star-Patterns:
  url: https://github.com/IsuruMS/Printing-Star-Patterns.git
  branches:
  - master
QuizBackend:
  url: https://github.com/SupulCFG/QuizBackend.git
  branches:
  - 2021-quiz-dev
  - 2021-quiz-dev-quiz-admins
  - main
  - quiz-2020-archive
Rate-Monotonic-Algorithm:
  url: https://github.com/IsuruMS/Rate-Monotonic-Algorithm.git
  branches:
  - master
Searching-Algorithms:
  url: https://github.com/IsuruMS/Searching-Algorithms.git
  branches:
  - master
Sorting-Algorithms:
  url: https://github.com/IsuruMS/Sorting-Algorithms.git
  branches:
  - master
Stack-Implementation:
  url: https://github.com/IsuruMS/Stack-Implementation.git
  branches:
  - master
sudoku:
  url: https://github.com/IsuruMS/sudoku.git
  branches:
  - main
  - master
trafficManagementSystem:
  url: https://github.com/IsuruMS/trafficManagementSystem.git
  branches:
  - main
usb_cam:
  url: https://github.com/IsuruMS/usb_cam.git
  branches:
  - develop
  - fix/camera_info_manager
  - master
  - ros2
audaxVQuiz:
  url: https://github.com/SupulCFG/audaxVQuiz.git
  branches:
  - master
  - raven
seds-juniors-astronight:
  url: https://github.com/SupulCFG/seds-juniors-astronight.git
  branches:
  - 2021-astronight-dev
  - archive-2020
  - main
